#!/bin/bash
# Copy the hardened profile from the image backup into the writable tmpfs
# Use cp without -a since we can't preserve root ownership as non-root user
cp -r /opt/firefox-profile/. /home/firefox/.mozilla/

# Configure PulseAudio client to use the mounted cookie file (cookie-based auth)
# instead of anonymous TCP. The cookie is generated by run.sh on the host and
# bind-mounted into the container at /home/firefox/.pulse-cookie.
mkdir -p /home/firefox/.config/pulse
if [[ -f /home/firefox/.pulse-cookie ]] && [[ -s /home/firefox/.pulse-cookie ]]; then
  echo "cookie-file = /home/firefox/.pulse-cookie" > /home/firefox/.config/pulse/client.conf
else
  # Fallback: disable cookie auth if no cookie was mounted (anonymous mode)
  echo "cookie-file = /dev/null" > /home/firefox/.config/pulse/client.conf
fi

exec firefox --no-remote --profile /home/firefox/.mozilla/firefox/hardened.default "$@"
